In [1]:
import numpy as np

# define an example array
y = np.array([1, 2, 3, 2, 1])

# one hot encode
one_hot = np.zeros((y.size, y.max()+1))
one_hot[np.arange(y.size), y] = 1

print(one_hot)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [2]:
import torch

# define an example tensor
y = torch.tensor([1, 2, 3, 2, 1])

# one hot encode
one_hot = torch.zeros((y.size(0), y.max().item()+1))
one_hot[torch.arange(y.size(0)), y] = 1

print(one_hot)

tensor([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.]])
